### ISSUE TITLE
Additional Package Request:  fcitx-skin-material

### ISSUE THREAD

**Issue by ghost** [microcai/gentoo-zh#5540]
Hello,

Could you please add fcitx-skin-material to the repository?
Upstream URL: https://github.com/hrko/fcitx-skin-material

**Comment by liangyongxiang** [comment]
I can help when I'm free, but not too early. Would you be interested in trying to write ebuild? I see the AUR script is relatively simple: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fcitx-skin-material

**Comment by ghost** [comment]
I will try when I have more time.
